"""initial tables

Revision ID: 23e9df865b68
Revises: 
Create Date: 2026-08-12 10:25:13.059419
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '23e9df865b68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
